CommunityManagement/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles import views
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    url(r'^navbar/', include('navbar.urls')),
    url(r'^carousel/', include('carousel.urls')),
    url(r'^article/', include('article.urls')),
    url(r'^announcement/', include('announcement.urls')),
    url(r'^link/', include('link.urls')),
    url(r'^authentication/', include('authentication.urls')),
    url(r'^activity/', include('activity.urls')),
    url(r'', include('website.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.static.serve, {'document_root': settings.STATIC_ROOT}, name="static"),
        url(r'^media/(?P<path>.*)$', views.static.serve, {'document_root': settings.MEDIA_ROOT}, name="media")
    ]

activity/urls.py
from django.conf.urls import url
from activity import views

urlpatterns = [
    url(r'^actor/(?P<activity_id>[0-9]+)/add/$', views.ActorCreateView.as_view(), name='actor-add'),
    url(r'^actor/(?P<activity_id>[0-9]+)/list/$', views.ActorListView.as_view(), name='actor-list'),
    url(r'^actor/(?P<pk>[0-9]+)/delete/$', views.ActorDeleteView.as_view(), name='actor-delete'),

    url(r'^task/add/$', views.TaskCreateView.as_view(), name='task-add'),
    url(r'^task/list/$', views.TaskListView.as_view(), name='task-list'),
    url(r'^task/(?P<pk>[0-9]+)/update/$', views.TaskUpdateView.as_view(), name='task-update'),
    url(r'^task/(?P<pk>[0-9]+)/delete/$', views.TaskDeleteView.as_view(), name='task-delete'),
    url(r'^task/(?P<pk>[0-9]+)/detail/$', views.TaskDetailView.as_view(), name='task-detail'),

    url(r'^activity/add/$', views.ActivityCreateView.as_view(), name='activity-add'),
    url(r'^activity/list/$', views.ActivityListView.as_view(), name='activity-list'),
    url(r'^activity/(?P<pk>[0-9]+)/update/$', views.ActivityUpdateView.as_view(), name='activity-update'),
    url(r'^activity/(?P<pk>[0-9]+)/delete/$', views.ActivityDeleteView.as_view(), name='activity-delete'),
    url(r'^activity/(?P<pk>[0-9]+)/detail/$', views.ActivityDetailView.as_view(), name='activity-detail'),
]

link/urls.py
from django.conf.urls import url
from link import views

urlpatterns = [
    url(r'^add/$', views.LinkCreateView.as_view(), name='link-add'),
    url(r'^list/$', views.LinkListView.as_view(), name='link-list'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.LinkUpdateView.as_view(), name='link-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.LinkDeleteView.as_view(), name='link-delete'),
]

activity/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from DjangoUeditor.models import UEditorField


class Activity(models.Model):
    title = models.CharField(max_length=128)
    content = UEditorField(imagePath="activity/images/", filePath="activity/files/")
    responsible_user = models.ForeignKey(User)
    address = models.CharField(max_length=128, blank=True, null=True)
    entry_closing_time = models.DateTimeField()
    start_time = models.DateTimeField()
    closing_time = models.DateTimeField()
    is_alternative = models.BooleanField(default=False)
    alternative_title = models.CharField(max_length=128, blank=True, null=True)

    def __unicode__(self):
        return self.title


class Actor(models.Model):
    name = models.CharField(max_length=32)
    SEX_CHOICE = (
        ('M', u'男'),
        ('F', u'女'),
    )
    student_id = models.CharField(max_length=16)
    sex = models.CharField(max_length=1, choices=SEX_CHOICE)
    level = models.SmallIntegerField()
    tel = models.CharField(max_length=11)
    alternative_content = models.TextField(blank=True, null=True)

    activity = models.ForeignKey(Activity)

    def __unicode__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True, null=True)
    responsible_user = models.ForeignKey(User)
    is_finished = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)
    comments = models.TextField(blank=True, null=True)

    activity = models.ForeignKey(Activity)

    def __unicode__(self):
        return self.name

announcement/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Announcement(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User)
    create_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return 'announcement of ' + str(self.create_time)

activity/views.py
from django.core.urlresolvers import reverse_lazy
from activity.models import Activity, Task, Actor
from utils.common_mixin import AjaxableResponseMixin, BaseMixin, FrontMixin
from django.db.models import Count
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from django.http import JsonResponse, Http404
from CommunityManagement.external_settings import PAGE_NUMBER


class ActivityCreateView(AjaxableResponseMixin, CreateView):
    model = Activity
    template_name_suffix = '_create_form'
    fields = ['title', 'content', 'responsible_user', 'address']
    success_url = reverse_lazy('activity-list')

    def get_context_data(self, *args, **kwargs):
        context = super(ActivityCreateView, self).get_context_data(*args, **kwargs)
        context['user_list'] = User.objects.filter(is_active=True)
        context['active_page'] = 'activity-add'
        return context

    def form_valid(self, form):
        form.instance.start_time = form.data['start_time'].replace('T', ' ')
        form.instance.closing_time = form.data['closing_time'].replace('T', ' ')
        form.instance.entry_closing_time = form.data['entry_closing_time'].replace('T', ' ')
        return super(ActivityCreateView, self).form_valid(form)


class ActivityListView(BaseMixin, ListView):
    model = Activity
    context_object_name = 'activity_list'
    queryset = Activity.objects.order_by('-start_time').annotate(actor_number=Count('actor'))

    def get_context_data(self, *args, **kwargs):
        context = super(ActivityListView, self).get_context_data(*args, **kwargs)
        context['active_page'] = 'activity-list'
        return context


class ActivityUpdateView(AjaxableResponseMixin, UpdateView):
    model = Activity
    template_name_suffix = '_update_form'
    fields = ['title', 'content', 'responsible_user', 'address']
    success_url = reverse_lazy('activity-list')
    context_object_name = 'activity'

    def get_context_data(self, *args, **kwargs):
        context = super(ActivityUpdateView, self).get_context_data(*args, **kwargs)
        context['user_list'] = User.objects.filter(is_active=True)
        context['active_page'] = 'activity-update'
        return context

    def form_valid(self, form):
        form.instance.start_time = form.data['start_time'].replace('T', ' ')
        form.instance.closing_time = form.data['closing_time'].replace('T', ' ')
        form.instance.entry_closing_time = form.data['entry_closing_time'].replace('T', ' ')
        return super(ActivityUpdateView, self).form_valid(form)


class ActivityDeleteView(AjaxableResponseMixin, DeleteView):
    model = Activity
    success_url = reverse_lazy('activity-list')

    def post(self, request, *args, **kwargs):
        super(ActivityDeleteView, self).post(request, *args, **kwargs)
        return JsonResponse({'state': 'success'})


class ActivityDetailView(FrontMixin, DetailView):
    model = Activity
    context_object_name = 'activity'
    template_name = 'activity/activity_detail.html'


class TaskCreateView(AjaxableResponseMixin, CreateView):
    pass


class TaskListView(BaseMixin, ListView):
    pass


class TaskUpdateView(AjaxableResponseMixin, UpdateView):
    pass


class TaskDeleteView(AjaxableResponseMixin, DeleteView):
    pass


class TaskDetailView(BaseMixin, DetailView):
    pass


class ActorCreateView(AjaxableResponseMixin, FrontMixin, CreateView):
    model = Actor
    template_name_suffix = '_create_form'
    fields = ['name', 'student_id', 'sex', 'level', 'tel']

    def get_context_data(self, *args, **kwargs):
        context = super(ActorCreateView, self).get_context_data(*args, **kwargs)
        context['activity'] = Activity.objects.get(pk=self.kwargs.get('activity_id'))
        return context

    def form_valid(self, form):
        form.instance.activity = Activity.objects.get(pk=self.kwargs.get('activity_id'))
        return super(ActorCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('activity-detail', kwargs={'pk': self.kwargs.get('activity_id')})


class ActorListView(BaseMixin, ListView):
    template_name = 'activity/actor_list.html'
    context_object_name = 'actor_list'
    model = Actor

    def get_context_data(self, *args, **kwargs):
        context = super(ActorListView, self).get_context_data(*args, **kwargs)
        context['active_page'] = 'actor-list'
        context['activity'] = Activity.objects.get(pk=self.kwargs.get('activity_id'))
        return context

    def get_queryset(self):
        queryset = Actor.objects.filter(activity=Activity.objects.get(pk=self.kwargs.get('activity_id')))
        return queryset


class ActorDeleteView(AjaxableResponseMixin, DeleteView):
    model = Actor
    success_url = reverse_lazy('activity-list')

    def post(self, request, *args, **kwargs):
        super(ActorDeleteView, self).post(request, *args, **kwargs)
        return JsonResponse({'state': 'success'})

templates/activity/activity_create_form.html
{% extends 'website/backend/settings/settings_base.html' %}

{% block option-title %}
    添加活动
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <form class="form-horizontal" id="data-form">
            <div class="form-group">
                <label for="title" class="col-sm-2 control-label">标题：</label>
                <div class="col-sm-9">
                    <input type="text" id="title" name="title" class="form-control" required>
                </div>
            </div>
            <div class="form-group">
                <label for="responsible_user" class="col-sm-2 control-label">负责人：</label>
                <div class="col-sm-9">
                    <select name="responsible_user" id="responsible_user" class="form-control">
                        {% for user in user_list %}
                            <option value="{{ user.id }}">{{ user.myuser.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="address" class="col-sm-2 control-label">地点：</label>
                <div class="col-sm-9">
                    <input type="text" id="address" name="address" class="form-control">
                </div>
            </div>
            <div class="form-group">
                <label for="start_time" class="col-sm-2 control-label">开始时间：</label>
                <div class="col-sm-9">
                    <input type="datetime-local" id="start_time" name="start_time" class="form-control" required>
                </div>
            </div>
            <div class="form-group">
                <label for="closing_time" class="col-sm-2 control-label">结束时间：</label>
                <div class="col-sm-9">
                    <input type="datetime-local" id="closing_time" name="closing_time" class="form-control" required>
                </div>
            </div>
            <div class="form-group">
                <label for="entry_closing_time" class="col-sm-2 control-label">报名截止：</label>
                <div class="col-sm-9">
                    <input type="datetime-local" id="entry_closing_time" name="entry_closing_time" class="form-control" required>
                </div>
            </div>
            <div class="form-group">
                <label for="ueditor_textarea_content" class="col-sm-2 control-label">简介：</label>
                <div class="col-sm-9">
                    <script id="id_content" name="content" style="display: inline-block;" type="text/plain"></script>
                    <script type="text/javascript">
                        var w = $('#id_content').parent().width;
                        var server_url = '/ueditor/controller/?imagePathFormat=activity/images/%(datetime)s%(rnd)s.%(extname)s&filePathFormat=activity/files/%(datetime)s%(rnd)s.%(extname)s';
                        var id_Content = UE.getEditor('id_content',{'initialFrameWidth': w, 'initialFrameHeight': 400, 'serverUrl': encodeURI(server_url)});
                        id_Content.ready(function(){});
                    </script>
                </div>
            </div>

            <button class="btn btn-info" id="submit-btn">添加</button>
            <input type="reset" name="reset" style="display: none;">
        </form>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#submit-btn').click(function(e){
            e.preventDefault();
            var options = {
                type:"POST",
                dataType:'json',
                url:'{% url "activity-add" %}',
                success:function(data){
                    var state = data.state;
                        if(state == 'success'){
                            showModal('success', "添加成功");
                        } else {
                            showModal('danger', "添加失败");
                        }
                        $('input[type=reset]').trigger('click');
                },
                error:function(data){
                    console.log(data);
                }
            };
            $('#data-form').ajaxSubmit(options);
        });
    </script>
{% endblock %}

templates/activity/activity_detail.html
{% extends 'website/frontend_base.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block external_head %}{% endblock %}


{% block left %}
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">活动详情</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h1>{{ activity.title }}</h1>
                        <h4>活动地点：{{ activity.address }}</h4>
                        <h4>开始时间：{{ activity.start_time|date:"Y-m-d " }}{{ activity.start_time|time:"H:i:s" }}</h4>
                        <h4>结束时间：{{ activity.closing_time|date:"Y-m-d " }}{{ activity.closing_time|time:"H:i:s" }}</h4>
                        <h4>报名截止：{{ activity.entry_closing_time|date:"Y-m-d " }}{{ activity.entry_closing_time|time:"H:i:s" }}</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <h3 class="text-info">活动介绍：</h3>
                        {{ activity.content|safe }}
                    </div>
                </div>
                <div class="row" style="margin-top: 20px;">
                    <div class="col-md-12 text-center">
                        <a href="{% url 'actor-add' activity.id %}" class="btn btn-primary btn-lg">活动报名</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}{% endblock %}

templates/activity/activity_list.html
{% extends 'website/backend/settings/settings_base.html' %}

{% block option-title %}
    活动列表
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <table class="table table-hover table-responsive table-condensed dashboard-table">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>活动名称</th>
                    <th>负责人</th>
                    <th>地点</th>
                    <th>开始时间</th>
                    <th>结束时间</th>
                    <th>报名截止时间</th>
                    <th>报名人数</th>
                    <th>动作</th>
                </tr>
            </thead>
            <tbody>
                {% for item in activity_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.title }}</td>
                        <td>{{ item.responsible_user.myuser.name }}</td>
                        <td>{{ item.address }}</td>
                        <td>{{ item.start_time|date:"Y-m-d " }}{{ item.start_time|time:"H:i:s" }}</td>
                        <td>{{ item.closing_time|date:"Y-m-d " }}{{ item.closing_time|time:"H:i:s" }}</td>
                        <td>{{ item.entry_closing_time|date:"Y-m-d " }}{{ item.entry_closing_time|time:"H:i:s" }}</td>
                        <td>{{ item.actor_number }}</td>
                        <td>
                            <a href="{% url 'activity-detail' item.pk %}" class="btn btn-info" role="button">详情</a>
                            &emsp;
                            <a href="{% url 'actor-list' item.id %}" class="btn btn-primary" role="button">报名详情</a>
                            &emsp;
                            <a href="{% url 'activity-update' item.pk %}" class="btn btn-warning" role="button">修改</a>
                            &emsp;
                            <button class="btn btn-danger" role="button" data-id="{{ item.id }}">删除</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('.btn-danger').on('click',
            function (e) {
                e.preventDefault();
                var dom_item = this;
                $.ajax({
                    type:"POST",
                    dataType:'json',
                    data:{},
                    url:'{% url "activity-delete" 00 %}'.replace('0', this.dataset['id']),
                    success:function(data){
                        var state = data.state;
                        if(state == 'success'){
                            dom_item.parentElement.parentElement.setAttribute('hidden','');
                            showModal('success', "删除成功！")
                        }
                    },
                    error:function(data){
                        alert(data);
                    }
                });
            })
    </script>
{% endblock %}

templates/activity/activity_settings_nav.html
<ul class="nav nav-sidebar">
    <li id="activity-list"><a href="{% url 'activity-list' %}">活动-列表</a></li>
    <li id="activity-add"><a href="{% url 'activity-add' %}">活动-添加</a></li>
    <li id="activity-update"><a href="{% url 'activity-list' %}">活动-更新</a></li>
    <li id="actor-list"><a href="{% url 'activity-list' %}">报名-详情</a></li>
</ul>

templates/activity/activity_update_form.html
{% extends 'website/backend/settings/settings_base.html' %}

{% block option-title %}
    更新活动
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <form class="form-horizontal" id="data-form">
            <div class="form-group">
                <label for="title" class="col-sm-1 control-label">标题：</label>
                <div class="col-sm-9">
                    <input type="text" id="title" name="title" class="form-control" required value="{{ activity.title }}">
                </div>
            </div>
            <div class="form-group">
                <label for="responsible_user" class="col-sm-1 control-label">负责人：</label>
                <div class="col-sm-9">
                    <select name="responsible_user" id="responsible_user" class="form-control">
                        {% for user in user_list %}
                            <option value="{{ user.id }}" {% if activity.responsible_user.id == user.id %} selected {% endif %}>{{ user.myuser.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="address" class="col-sm-1 control-label">地点：</label>
                <div class="col-sm-9">
                    <input type="text" id="address" name="address" class="form-control" value="{{ activity.address }}">
                </div>
            </div>
            <div class="form-group">
                <label for="start_time" class="col-sm-1 control-label">开始时间：</label>
                <div class="col-sm-9">
                    <input type="datetime-local" id="start_time" name="start_time" class="form-control" required value="{{ activity.start_time|date:"Y-m-d" }}T{{ activity.start_time|time:"H:i:s" }}">
                </div>
            </div>
            <div class="form-group">
                <label for="closing_time" class="col-sm-1 control-label">结束时间：</label>
                <div class="col-sm-9">
                    <input type="datetime-local" id="closing_time" name="closing_time" class="form-control" required value="{{ activity.closing_time|date:"Y-m-d" }}T{{ activity.closing_time|time:"H:i:s" }}">
                </div>
            </div>
            <div class="form-group">
                <label for="entry_closing_time" class="col-sm-1 control-label">报名截止：</label>
                <div class="col-sm-9">
                    <input type="datetime-local" id="entry_closing_time" name="entry_closing_time" class="form-control" required value="{{ activity.entry_closing_time|date:"Y-m-d" }}T{{ activity.entry_closing_time|time:"H:i:s" }}">
                </div>
            </div>
            <div class="form-group">
                <label for="ueditor_textarea_content" class="col-sm-1 control-label">简介：</label>
                <div class="col-sm-9">
                    <script id="id_content" name="content" style="display: inline-block;" type="text/plain">{{ activity.content|safe }}</script>
                    <script type="text/javascript">
                        var w = $('#id_content').parent().width;
                        var server_url = '/ueditor/controller/?imagePathFormat=activity/images/%(datetime)s%(rnd)s.%(extname)s&filePathFormat=activity/files/%(datetime)s%(rnd)s.%(extname)s';
                        var id_Content = UE.getEditor('id_content',{'initialFrameWidth': w, 'initialFrameHeight': 400, 'serverUrl': encodeURI(server_url)});
                        id_Content.ready(function(){});
                    </script>
                </div>
            </div>

            <button class="btn btn-info" id="submit-btn">更新</button>
        </form>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#submit-btn').click(function(e){
            e.preventDefault();
            var options = {
                type:"POST",
                dataType:'json',
                url:'{% url "activity-update" activity.id %}',
                success:function(data){
                    var state = data.state;
                        if(state == 'success'){
                            showModal('success', "更新成功");
                        } else {
                            showModal('danger', "更新失败");
                        }
                },
                error:function(data){
                    console.log(data);
                }
            };
            $('#data-form').ajaxSubmit(options);
        });
    </script>
{% endblock %}

templates/activity/activity_weight.html
<div class="col-md-12">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">最新活动</h3>
        </div>
        <div class="list-group">
        {% for activity in activity_list %}
            <a href="{% url 'activity-detail' activity.id %}" class="list-group-item">
                <h4 class="list-group-item-heading">{{ activity.title }}</h4>
                <p class="list-group-item-text">地点：{{ activity.address }}</p>
                <p class="list-group-item-text text-info">开始时间：{{ activity.start_time|date:"Y-m-d" }}&nbsp;{{ activity.start_time|time:"H:i:s" }}</p>
            </a>
        {% endfor %}
        {% if has_more_activity %}
            <a href="{% url 'activity-list' %}" class="list-group-item text-right">更多...</a>
        {% endif %}
        </div>
    </div>
</div>

templates/activity/actor_create_form.html
{% extends 'website/frontend_base.html' %}

{% block title %}{{ activity.title }}{% endblock %}

{% block external_head %}{% endblock %}


{% block left %}
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">活动报名</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h1>{{ activity.title }}</h1>
                        <h4>活动地点：{{ activity.address }}</h4>
                        <h4>开始时间：{{ activity.start_time|date:"Y-m-d " }}{{ activity.start_time|time:"H:i:s" }}</h4>
                        <h4>结束时间：{{ activity.closing_time|date:"Y-m-d " }}{{ activity.closing_time|time:"H:i:s" }}</h4>
                        <h4>报名截止：{{ activity.entry_closing_time|date:"Y-m-d " }}{{ activity.entry_closing_time|time:"H:i:s" }}</h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <form class="form-horizontal" method="post" id="data-form" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label">姓名:</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="name" name="name" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="student_id" class="col-sm-2 control-label">学号:</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" id="student_id" name="student_id" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="level" class="col-sm-2 control-label">入学年份:</label>
                                <div class="col-sm-9">
                                    <input type="number" class="form-control" id="level" name="level" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="sex" class="col-sm-2 control-label">性别:</label>
                                <div class="col-sm-9">
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="sex" value="M" checked>
                                            男
                                        </label>
                                        <label>
                                            <input type="radio" name="sex" value="F">
                                            女
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="tel" class="col-sm-2 control-label">电话:</label>
                                <div class="col-sm-9">
                                    <input type="tel" class="form-control" id="tel" name="tel" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-2">
                                    <button type="submit" class="btn btn-primary" id="submit-btn">提交</button>
                                </div>
                                <div class="col-sm-offset-3 col-sm-2">
                                    <button type="reset" class="btn btn-warning">重置</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}

{% endblock %}

templates/activity/actor_list.html
{% extends 'website/backend/settings/settings_base.html' %}

{% block option-title %}
    参与者列表
{% endblock %}

{% block content %}
    <div class="col-md-12">
        <h2 class="text-info">{{ activity.title }}</h2>
        <table class="table table-hover table-responsive table-condensed dashboard-table">
            <thead>
                <tr>
                    <th>序号</th>
                    <th>学号</th>
                    <th>姓名</th>
                    <th>入学年份</th>
                    <th>性别</th>
                    <th>电话</th>
                    <th>动作</th>
                </tr>
            </thead>
            <tbody>
                {% for item in actor_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.student_id }}</td>
                        <td>{{ item.name }}</td>
                        <td>{{ item.level }}</td>
                        <td>
                            {% if item.sex == 'M' %}
                                男
                            {% else %}
                                女
                            {% endif %}
                        </td>
                        <td>{{ item.tel }}</td>
                        <td>
                            <button class="btn btn-danger" role="button" data-id="{{ item.id }}">删除</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% include 'utils/modal.html' %}
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('.btn-danger').on('click',
            function (e) {
                e.preventDefault();
                var dom_item = this;
                $.ajax({
                    type:"POST",
                    dataType:'json',
                    data:{},
                    url:'{% url "actor-delete" 00 %}'.replace('0', this.dataset['id']),
                    success:function(data){
                        var state = data.state;
                        if(state == 'success'){
                            dom_item.parentElement.parentElement.setAttribute('hidden','');
                            showModal('success', "删除成功！")
                        }
                    },
                    error:function(data){
                        alert(data);
                    }
                });
            })
    </script>
{% endblock %}